server.port: 9000
spring:
  application:
    name: kuke-board-article-service
  datasource:
    url: jdbc:mysql://localhost:3306/article
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
